#!/bin/bash
# extrait les définitions par terme 
# format d'entrée : Gilles
# sorties : file.Noyau : toutes les définitions d'un terme (non trié)

if (( $# != "2" )) ; then
echo "usage : extract-defNoyau [-f | -e | -d] [file]" 
echo "-f : french  -e : english  -d : deutsch" 
exit
fi

if (( $1 == "-f" )) ; then  
L="#fra"
elif (( $1 == "-e" )) ; then
L="#eng"
elif (( $1 == "-d")) ; then
L="#deu"
fi

# extraction des termes définis (origine) et des définitions destinations 

egrep '(^[ ,	]*-O- '+$L+'\||^[ ,	]*-D- #def)' $2  | awk ' { gsub(/#.*\|/, "") ;
										 					   gsub(/#{/,""); gsub(/}#/,""); print ;}' > $2.Noyau