#!/usr/bin/env bash
cat<<EOF
/* this file is automatically generated by generate_codes.sh */
package org.getalp.dbnary.languages.ces;

import java.util.HashMap;
import org.getalp.LangTools;

public class CzechLanguageCodes extends LangTools {
    static HashMap<String, String> h = new HashMap<>();

    static {
EOF
cat czech_iso_639-1_nonumbers_wpfixed.txt | awk -F'\t' '{ print "\th.put(\"" $4 "\", \"" $3 "\");" }'
cat<<EOF
    }

    public static String threeLettersCode(String s) {
	return threeLettersCode(h, s);
    }
}
EOF
