SELECT ?cl, ?cs, ?cp, ?ct WHERE {
  ?o a qb:Observation ;
     qb:dataSet dbnary:dbnaryStatisticsCube ;
     dbnary:lexicalEntryCount ?cl ;
     dbnary:lexicalSenseCount ?cs ;
     dbnary:pageCount ?cp ;
     dbnary:translationsCount ?ct . }

     SELECT ?slanguage ?count
     WHERE {
       ?observation a qb:Observation.
       ?observation qb:dataSet ?translationsDataCube.
       ?observation dbnary:wiktionaryDumpVersion ?version.
       ?observation dbnary:observationLanguage ?slanguage.
       ?observation lime:language "Total".
       ?observation dbnary:count ?count.
      }

SELECT ?s ?o
WHERE {
  ?s dbnary:wiktionaryDumpVersion ?o.
 }