#!/bin/bash

VERSION=3.0.0b4
JAVA=java

$JAVA -Djava.net.useSystemProxies=true \
-cp ${HOME}/.m2/repository/org/getalp/dbnary-commands/$VERSION/dbnary-commands-$VERSION-jar-with-dependencies.jar \
    org.getalp.dbnary.cli.Sed "$@"


