#!/bin/bash

VERSION=2.4.2
JAVA=java

$JAVA -Djava.net.useSystemProxies=true \
-cp ${HOME}/.m2/repository/org/getalp/dbnary-commands/$VERSION/dbnary-commands-$VERSION-jar-with-dependencies.jar \
    org.getalp.dbnary.cli.Sed "$@"


