version: '3'

services:
  fuseki:
    build:
      context: .
    ports:
      - "3030:3030"
    volumes:
      - ./data:/data/fuseki
    restart: unless-stopped
    environment:
      - ADMIN_PASSWORD=admin
