/**
 * 
 */
package org.getalp.dbnary.eng;

import java.util.HashMap;

import org.getalp.blexisma.api.ISO639_3;

/**
 * @author Mariam
 *
 */
public class EnglishLangToCode {
	
	
	static HashMap<String,String> englishLangNameToLangCode = new HashMap<String,String>();
	static{
		englishLangNameToLangCode.put("Abkhaz","ab");
		englishLangNameToLangCode.put("Acehnese","ace");
		englishLangNameToLangCode.put("Acholi","ach");
		englishLangNameToLangCode.put("Adangme","ada");
		englishLangNameToLangCode.put("Adyghe","ady");
		englishLangNameToLangCode.put("Afar","aa");
		englishLangNameToLangCode.put("Afrihili","afh");
		englishLangNameToLangCode.put("Afrikaans","af");
		englishLangNameToLangCode.put("Ainu","ain");
		englishLangNameToLangCode.put("Akan","ak");
		englishLangNameToLangCode.put("Akkadian","akk");
		englishLangNameToLangCode.put("Albanian","sq");
		englishLangNameToLangCode.put("Alemannic German","gsw");
		englishLangNameToLangCode.put("Aleut","ale");
		englishLangNameToLangCode.put("Amharic","am");
		englishLangNameToLangCode.put("Ancient Greek","grc");
		englishLangNameToLangCode.put("Angika","anp");
		englishLangNameToLangCode.put("Arabic","ar");
		englishLangNameToLangCode.put("Aragonese","an");
		englishLangNameToLangCode.put("Aramaic","arc");
		englishLangNameToLangCode.put("Arapaho","arp");
		englishLangNameToLangCode.put("Arawak","arw");
		englishLangNameToLangCode.put("Armenian","hy");
		englishLangNameToLangCode.put("Aromanian","rup");
		englishLangNameToLangCode.put("Assamese","as");
		englishLangNameToLangCode.put("Asturian","ast");
		englishLangNameToLangCode.put("Avar","av");
		englishLangNameToLangCode.put("Avestan","ae");
		englishLangNameToLangCode.put("Awadhi","awa");
		englishLangNameToLangCode.put("Aymara","ay");
		englishLangNameToLangCode.put("Azeri","az");
		englishLangNameToLangCode.put("Balinese","ban");
		englishLangNameToLangCode.put("Baluchi","bal");
		englishLangNameToLangCode.put("Bambara","bm");
		englishLangNameToLangCode.put("Basaa","bas");
		englishLangNameToLangCode.put("Bashkir","ba");
		englishLangNameToLangCode.put("Basque","eu");
		englishLangNameToLangCode.put("Beja","bej");
		englishLangNameToLangCode.put("Belarusian","be");
		englishLangNameToLangCode.put("Bemba","bem");
		englishLangNameToLangCode.put("Bengali","bn");
		englishLangNameToLangCode.put("Bhojpuri","bho");
		englishLangNameToLangCode.put("Bikol","bik");
		englishLangNameToLangCode.put("Bini","bin");
		englishLangNameToLangCode.put("Bislama","bi");
		englishLangNameToLangCode.put("Blackfoot","bla");
		englishLangNameToLangCode.put("Blin","byn");
		englishLangNameToLangCode.put("Bosnian","bs");
		englishLangNameToLangCode.put("Braj","bra");
		englishLangNameToLangCode.put("Breton","br");
		englishLangNameToLangCode.put("Buginese","bug");
		englishLangNameToLangCode.put("Bulgarian","bg");
		englishLangNameToLangCode.put("Burmese","my");
		englishLangNameToLangCode.put("Buryat","bua");
		englishLangNameToLangCode.put("Caddo","cad");
		englishLangNameToLangCode.put("Catalan","ca");
		englishLangNameToLangCode.put("Cebuano","ceb");
		englishLangNameToLangCode.put("Chagatai","chg");
		englishLangNameToLangCode.put("Chamorro","ch");
		englishLangNameToLangCode.put("Chechen","ce");
		englishLangNameToLangCode.put("Cherokee","chr");
		englishLangNameToLangCode.put("Cheyenne","chy");
		englishLangNameToLangCode.put("Chibcha","chb");
		englishLangNameToLangCode.put("Chichewa","ny");
		englishLangNameToLangCode.put("Chinook Jargon","chn");
		englishLangNameToLangCode.put("Chipewyan","chp");
		englishLangNameToLangCode.put("Choctaw","cho");
		englishLangNameToLangCode.put("Chuukese","chk");
		englishLangNameToLangCode.put("Chuvash","cv");
		englishLangNameToLangCode.put("Classical Newari","nwc");
		englishLangNameToLangCode.put("Classical Syriac","syc");
		englishLangNameToLangCode.put("Coptic","cop");
		englishLangNameToLangCode.put("Cornish","kw");
		englishLangNameToLangCode.put("Corsican","co");
		englishLangNameToLangCode.put("Cree","cr");
		englishLangNameToLangCode.put("Creek","mus");
		englishLangNameToLangCode.put("Crimean Tatar","crh");
		englishLangNameToLangCode.put("Croatian","hr");
		englishLangNameToLangCode.put("Czech","cs");
		englishLangNameToLangCode.put("Dakota","dak");
		englishLangNameToLangCode.put("Danish","da");
		englishLangNameToLangCode.put("Dargwa","dar");
		englishLangNameToLangCode.put("Dhivehi","dv");
		englishLangNameToLangCode.put("Dinka","din");
		englishLangNameToLangCode.put("Dogri","doi");
		englishLangNameToLangCode.put("Dogrib","dgr");
		englishLangNameToLangCode.put("Duala","dua");
		englishLangNameToLangCode.put("Dutch","nl");
		englishLangNameToLangCode.put("Dyula","dyu");
		englishLangNameToLangCode.put("Dzongkha","dz");
		englishLangNameToLangCode.put("Eastern Frisian","frs");
		englishLangNameToLangCode.put("Efik","efi");
		englishLangNameToLangCode.put("Egyptian","egy");
		englishLangNameToLangCode.put("Ekajuk","eka");
		englishLangNameToLangCode.put("Elamite","elx");
		englishLangNameToLangCode.put("English","en");
		englishLangNameToLangCode.put("Erzya","myv");
		englishLangNameToLangCode.put("Esperanto","eo");
		englishLangNameToLangCode.put("Estonian","et");
		englishLangNameToLangCode.put("Ewe","ee");
		englishLangNameToLangCode.put("Ewondo","ewo");
		englishLangNameToLangCode.put("Fanti","fat");
		englishLangNameToLangCode.put("Faroese","fo");
		englishLangNameToLangCode.put("Fijian","fj");
		englishLangNameToLangCode.put("Finnish","fi");
		englishLangNameToLangCode.put("Fon","fon");
		englishLangNameToLangCode.put("French","fr");
		englishLangNameToLangCode.put("Friulian","fur");
		englishLangNameToLangCode.put("Fula","ff");
		englishLangNameToLangCode.put("Ga","gaa");
		englishLangNameToLangCode.put("Galibi Carib","car");
		englishLangNameToLangCode.put("Galician","gl");
		englishLangNameToLangCode.put("Gayo","gay");
		englishLangNameToLangCode.put("Gbaya","gba");
		englishLangNameToLangCode.put("Ge'ez","gez");
		englishLangNameToLangCode.put("Georgian","ka");
		englishLangNameToLangCode.put("German","de");
		englishLangNameToLangCode.put("Gilbertese","gil");
		englishLangNameToLangCode.put("Gondi","gon");
		englishLangNameToLangCode.put("Gorontalo","gor");
		englishLangNameToLangCode.put("Gothic","got");
		englishLangNameToLangCode.put("Grebo","grb");
		englishLangNameToLangCode.put("Greek","el");
		englishLangNameToLangCode.put("Greenlandic","kl");
		englishLangNameToLangCode.put("Guaraní","gn");
		englishLangNameToLangCode.put("Gujarati","gu");
		englishLangNameToLangCode.put("Gwich'in","gwi");
		englishLangNameToLangCode.put("Haida","hai");
		englishLangNameToLangCode.put("Haitian Creole","ht");
		englishLangNameToLangCode.put("Hausa","ha");
		englishLangNameToLangCode.put("Hawaiian","haw");
		englishLangNameToLangCode.put("Hebrew","he");
		englishLangNameToLangCode.put("Herero","hz");
		englishLangNameToLangCode.put("Hiligaynon","hil");
		englishLangNameToLangCode.put("Hindi","hi");
		englishLangNameToLangCode.put("Hiri Motu","ho");
		englishLangNameToLangCode.put("Hittite","hit");
		englishLangNameToLangCode.put("Hmong","hmn");
		englishLangNameToLangCode.put("Hungarian","hu");
		englishLangNameToLangCode.put("Hupa","hup");
		englishLangNameToLangCode.put("Iban","iba");
		englishLangNameToLangCode.put("Icelandic","is");
		englishLangNameToLangCode.put("Ido","io");
		englishLangNameToLangCode.put("Igbo","ig");
		englishLangNameToLangCode.put("Ilocano","ilo");
		englishLangNameToLangCode.put("Inari Sami","smn");
		englishLangNameToLangCode.put("Indonesian","id");
		englishLangNameToLangCode.put("Ingush","inh");
		englishLangNameToLangCode.put("Interlingua","ia");
		englishLangNameToLangCode.put("Interlingue","ie");
		englishLangNameToLangCode.put("Inuktitut","iu");
		englishLangNameToLangCode.put("Inupiak","ik");
		englishLangNameToLangCode.put("Irish","ga");
		englishLangNameToLangCode.put("Italian","it");
		englishLangNameToLangCode.put("Japanese","ja");
		englishLangNameToLangCode.put("Javanese","jv");
		englishLangNameToLangCode.put("Jingpho","kac");
		englishLangNameToLangCode.put("Judeo-Arabic","jrb");
		englishLangNameToLangCode.put("Judeo-Persian","jpr");
		englishLangNameToLangCode.put("Kabardian","kbd");
		englishLangNameToLangCode.put("Kabyle","kab");
		englishLangNameToLangCode.put("Kalmyk","xal");
		englishLangNameToLangCode.put("Kamba","kam");
		englishLangNameToLangCode.put("Kannada","kn");
		englishLangNameToLangCode.put("Kanuri","kr");
		englishLangNameToLangCode.put("Kapampangan","pam");
		englishLangNameToLangCode.put("Karachay-Balkar","krc");
		englishLangNameToLangCode.put("Karakalpak","kaa");
		englishLangNameToLangCode.put("Karelian","krl");
		englishLangNameToLangCode.put("Kashmiri","ks");
		englishLangNameToLangCode.put("Kashubian","csb");
		englishLangNameToLangCode.put("Kazakh","kk");
		englishLangNameToLangCode.put("Khasi","kha");
		englishLangNameToLangCode.put("Khmer","km");
		englishLangNameToLangCode.put("Khotanese","kho");
		englishLangNameToLangCode.put("Kikuyu","ki");
		englishLangNameToLangCode.put("Kimbundu","kmb");
		englishLangNameToLangCode.put("Kinyarwanda","rw");
		englishLangNameToLangCode.put("Kirundi","rn");
		englishLangNameToLangCode.put("Komi-Zyrian","kv");
		englishLangNameToLangCode.put("Kongo","kg");
		englishLangNameToLangCode.put("Konkani","kok");
		englishLangNameToLangCode.put("Korean","ko");
		englishLangNameToLangCode.put("Kosraean","kos");
		englishLangNameToLangCode.put("Kpelle","kpe");
		englishLangNameToLangCode.put("Kumyk","kum");
		englishLangNameToLangCode.put("Kurdish","ku");
		englishLangNameToLangCode.put("Kurukh","kru");
		englishLangNameToLangCode.put("Kutenai","kut");
		englishLangNameToLangCode.put("Kwanyama","kj");
		englishLangNameToLangCode.put("Kyrgyz","ky");
		englishLangNameToLangCode.put("Ladino","lad");
		englishLangNameToLangCode.put("Lahnda","lah");
		englishLangNameToLangCode.put("Lamba","lam");
		englishLangNameToLangCode.put("Lao","lo");
		englishLangNameToLangCode.put("Latin","la");
		englishLangNameToLangCode.put("Latvian","lv");
		englishLangNameToLangCode.put("Lenape","del");
		englishLangNameToLangCode.put("Lezgi","lez");
		englishLangNameToLangCode.put("Limburgish","li");
		englishLangNameToLangCode.put("Lingala","ln");
		englishLangNameToLangCode.put("Lithuanian","lt");
		englishLangNameToLangCode.put("Lojban","jbo");
		englishLangNameToLangCode.put("Low German","nds");
		englishLangNameToLangCode.put("Lower Sorbian","dsb");
		englishLangNameToLangCode.put("Lozi","loz");
		englishLangNameToLangCode.put("Luba-Katanga","lu");
		englishLangNameToLangCode.put("Luganda","lg");
		englishLangNameToLangCode.put("Luiseno","lui");
		englishLangNameToLangCode.put("Lule Sami","smj");
		englishLangNameToLangCode.put("Lunda","lun");
		englishLangNameToLangCode.put("Luo","luo");
		englishLangNameToLangCode.put("Luxembourgish","lb");
		englishLangNameToLangCode.put("Maasai","mas");
		englishLangNameToLangCode.put("Macedonian","mk");
		englishLangNameToLangCode.put("Madurese","mad");
		englishLangNameToLangCode.put("Magahi","mag");
		englishLangNameToLangCode.put("Maithili","mai");
		englishLangNameToLangCode.put("Makasar","mak");
		englishLangNameToLangCode.put("Malagasy","mg");
		englishLangNameToLangCode.put("Malay","ms");
		englishLangNameToLangCode.put("Malayalam","ml");
		englishLangNameToLangCode.put("Maltese","mt");
		englishLangNameToLangCode.put("Manchu","mnc");
		englishLangNameToLangCode.put("Mandar","mdr");
		englishLangNameToLangCode.put("Mandarin","zh");
		englishLangNameToLangCode.put("Mandingo","man");
		englishLangNameToLangCode.put("Manipuri","mni");
		englishLangNameToLangCode.put("Manx","gv");
		englishLangNameToLangCode.put("Maori","mi");
		englishLangNameToLangCode.put("Mapudungun","arn");
		englishLangNameToLangCode.put("Marathi","mr");
		englishLangNameToLangCode.put("Mari","chm");
		englishLangNameToLangCode.put("Marshallese","mh");
		englishLangNameToLangCode.put("Marwari","mwr");
		englishLangNameToLangCode.put("Mende","men");
		englishLangNameToLangCode.put("Middle Dutch","dum");
		englishLangNameToLangCode.put("Middle English","enm");
		englishLangNameToLangCode.put("Middle French","frm");
		englishLangNameToLangCode.put("Middle High German","gmh");
		englishLangNameToLangCode.put("Middle Irish","mga");
		englishLangNameToLangCode.put("Middle Persian","pal");
		englishLangNameToLangCode.put("Mi'kmaq","mic");
		englishLangNameToLangCode.put("Minangkabau","min");
		englishLangNameToLangCode.put("Mirandese","mwl");
		englishLangNameToLangCode.put("Mizo","lus");
		englishLangNameToLangCode.put("Mohawk","moh");
		englishLangNameToLangCode.put("Moksha","mdf");
		englishLangNameToLangCode.put("Mongo","lol");
		englishLangNameToLangCode.put("Mongolian","mn");
		englishLangNameToLangCode.put("More","mos");
		englishLangNameToLangCode.put("Nauruan","na");
		englishLangNameToLangCode.put("Navajo","nv");
		englishLangNameToLangCode.put("Ndonga","ng");
		englishLangNameToLangCode.put("Neapolitan","nap");
		englishLangNameToLangCode.put("Nepali","ne");
		englishLangNameToLangCode.put("Newari","new");
		englishLangNameToLangCode.put("Nias","nia");
		englishLangNameToLangCode.put("Niuean","niu");
		englishLangNameToLangCode.put("N'Ko","nqo");
		englishLangNameToLangCode.put("Nogai","nog");
		englishLangNameToLangCode.put("North Frisian","frr");
		englishLangNameToLangCode.put("Northern Ndebele","nd");
		englishLangNameToLangCode.put("Northern Sami","se");
		englishLangNameToLangCode.put("Northern Sotho","nso");
		englishLangNameToLangCode.put("Norwegian","no");
		englishLangNameToLangCode.put("Norwegian Bokmål","nb");
		englishLangNameToLangCode.put("Norwegian Nynorsk","nn");
		englishLangNameToLangCode.put("Nyamwezi","nym");
		englishLangNameToLangCode.put("Nyankole","nyn");
		englishLangNameToLangCode.put("Nyoro","nyo");
		englishLangNameToLangCode.put("Nzima","nzi");
		englishLangNameToLangCode.put("Occitan","oc");
		englishLangNameToLangCode.put("Ojibwe","oj");
		englishLangNameToLangCode.put("Old Church Slavonic","cu");
		englishLangNameToLangCode.put("Old English","ang");
		englishLangNameToLangCode.put("Old French","fro");
		englishLangNameToLangCode.put("Old High German","goh");
		englishLangNameToLangCode.put("Old Irish","sga");
		englishLangNameToLangCode.put("Old Javanese","kaw");
		englishLangNameToLangCode.put("Old Norse","non");
		englishLangNameToLangCode.put("Old Provençal","pro");
		englishLangNameToLangCode.put("Old Persian","peo");
		englishLangNameToLangCode.put("Oriya","or");
		englishLangNameToLangCode.put("Oromo","om");
		englishLangNameToLangCode.put("Osage","osa");
		englishLangNameToLangCode.put("Ossetian","os");
		englishLangNameToLangCode.put("Ottoman Turkish","ota");
		englishLangNameToLangCode.put("Pahouin","fan");
		englishLangNameToLangCode.put("Palauan","pau");
		englishLangNameToLangCode.put("Pali","pi");
		englishLangNameToLangCode.put("Pangasinan","pag");
		englishLangNameToLangCode.put("Papiamentu","pap");
		englishLangNameToLangCode.put("Pashto","ps");
		englishLangNameToLangCode.put("Persian","fa");
		englishLangNameToLangCode.put("Phoenician","phn");
		englishLangNameToLangCode.put("Pohnpeian","pon");
		englishLangNameToLangCode.put("Polish","pl");
		englishLangNameToLangCode.put("Portuguese","pt");
		englishLangNameToLangCode.put("Punjabi","pa");
		englishLangNameToLangCode.put("Quechua","qu");
		englishLangNameToLangCode.put("Rajasthani","raj");
		englishLangNameToLangCode.put("Rapa Nui","rap");
		englishLangNameToLangCode.put("Rarotongan","rar");
		englishLangNameToLangCode.put("Romani","rom");
		englishLangNameToLangCode.put("Romanian","ro");
		englishLangNameToLangCode.put("Romansch","rm");
		englishLangNameToLangCode.put("Russian","ru");
		englishLangNameToLangCode.put("Samaritan Aramaic","sam");
		englishLangNameToLangCode.put("Samoan","sm");
		englishLangNameToLangCode.put("Sandawe","sad");
		englishLangNameToLangCode.put("Sango","sg");
		englishLangNameToLangCode.put("Sanskrit","sa");
		englishLangNameToLangCode.put("Santali","sat");
		englishLangNameToLangCode.put("Sardinian","sc");
		englishLangNameToLangCode.put("Sasak","sas");
		englishLangNameToLangCode.put("Scots","sco");
		englishLangNameToLangCode.put("Scottish Gaelic","gd");
		englishLangNameToLangCode.put("Selkup","sel");
		englishLangNameToLangCode.put("Serbian","sr");
		englishLangNameToLangCode.put("Serbo-Croatian","sh");
		englishLangNameToLangCode.put("Serer","srr");
		englishLangNameToLangCode.put("Shan","shn");
		englishLangNameToLangCode.put("Shona","sn");
		englishLangNameToLangCode.put("Sichuan Yi","ii");
		englishLangNameToLangCode.put("Sicilian","scn");
		englishLangNameToLangCode.put("Sidamo","sid");
		englishLangNameToLangCode.put("Sindhi","sd");
		englishLangNameToLangCode.put("Sinhalese","si");
		englishLangNameToLangCode.put("Siska","tog");
		englishLangNameToLangCode.put("Skolt Sami","sms");
		englishLangNameToLangCode.put("Slavey","den");
		englishLangNameToLangCode.put("Slovak","sk");
		englishLangNameToLangCode.put("Slovene","sl");
		englishLangNameToLangCode.put("Sogdian","sog");
		englishLangNameToLangCode.put("Somali","so");
		englishLangNameToLangCode.put("Soninke","snk");
		englishLangNameToLangCode.put("Sotho","st");
		englishLangNameToLangCode.put("Southern Altai","alt");
		englishLangNameToLangCode.put("Southern Ndebele","nr");
		englishLangNameToLangCode.put("Southern Sami","sma");
		englishLangNameToLangCode.put("Spanish","es");
		englishLangNameToLangCode.put("Sranan Tongo","srn");
		englishLangNameToLangCode.put("Sukuma","suk");
		englishLangNameToLangCode.put("Sumerian","sux");
		englishLangNameToLangCode.put("Sundanese","su");
		englishLangNameToLangCode.put("Susu","sus");
		englishLangNameToLangCode.put("Swahili","sw");
		englishLangNameToLangCode.put("Swati","ss");
		englishLangNameToLangCode.put("Swedish","sv");
		englishLangNameToLangCode.put("Syriac","syr");
		englishLangNameToLangCode.put("Tagalog","tl");
		englishLangNameToLangCode.put("Tahitian","ty");
		englishLangNameToLangCode.put("Tajik","tg");
		englishLangNameToLangCode.put("Tamashek","tmh");
		englishLangNameToLangCode.put("Tamil","ta");
		englishLangNameToLangCode.put("Tatar","tt");
		englishLangNameToLangCode.put("Telugu","te");
		englishLangNameToLangCode.put("Template:fil","fil");
		englishLangNameToLangCode.put("Template:mis","mis");
		englishLangNameToLangCode.put("Template:mo","mo");
		englishLangNameToLangCode.put("Template:tlh","tlh");
		englishLangNameToLangCode.put("Template:zbl","zbl");
		englishLangNameToLangCode.put("Template:zxx","zxx");
		englishLangNameToLangCode.put("Tereno","ter");
		englishLangNameToLangCode.put("Tetum","tet");
		englishLangNameToLangCode.put("Thai","th");
		englishLangNameToLangCode.put("Tibetan","bo");
		englishLangNameToLangCode.put("Tigre","tig");
		englishLangNameToLangCode.put("Tigrinya","ti");
		englishLangNameToLangCode.put("Timne","tem");
		englishLangNameToLangCode.put("Tivi","tiv");
		englishLangNameToLangCode.put("Tlingit","tli");
		englishLangNameToLangCode.put("Tok Pisin","tpi");
		englishLangNameToLangCode.put("Tokelauan","tkl");
		englishLangNameToLangCode.put("Tongan","to");
		englishLangNameToLangCode.put("Translingual","mul");
		englishLangNameToLangCode.put("Tshiluba","lua");
		englishLangNameToLangCode.put("Tsimshian","tsi");
		englishLangNameToLangCode.put("Tsonga","ts");
		englishLangNameToLangCode.put("Tswana","tn");
		englishLangNameToLangCode.put("Tumbuka","tum");
		englishLangNameToLangCode.put("Turkish","tr");
		englishLangNameToLangCode.put("Turkmen","tk");
		englishLangNameToLangCode.put("Tuvaluan","tvl");
		englishLangNameToLangCode.put("Tuvan","tyv");
		englishLangNameToLangCode.put("Twi","tw");
		englishLangNameToLangCode.put("Udmurt","udm");
		englishLangNameToLangCode.put("Ugaritic","uga");
		englishLangNameToLangCode.put("Ukrainian","uk");
		englishLangNameToLangCode.put("Umbundu","umb");
		englishLangNameToLangCode.put("Undetermined","und");
		englishLangNameToLangCode.put("Upper Sorbian","hsb");
		englishLangNameToLangCode.put("Urdu","ur");
		englishLangNameToLangCode.put("Uyghur","ug");
		englishLangNameToLangCode.put("Uzbek","uz");
		englishLangNameToLangCode.put("Vai","vai");
		englishLangNameToLangCode.put("Venda","ve");
		englishLangNameToLangCode.put("Vietnamese","vi");
		englishLangNameToLangCode.put("Volapük","vo");
		englishLangNameToLangCode.put("Votic","vot");
		englishLangNameToLangCode.put("Walamo","wal");
		englishLangNameToLangCode.put("Walloon","wa");
		englishLangNameToLangCode.put("Waray-Waray","war");
		englishLangNameToLangCode.put("Washo","was");
		englishLangNameToLangCode.put("Welsh","cy");
		englishLangNameToLangCode.put("West Frisian","fy");
		englishLangNameToLangCode.put("Wolof","wo");
		englishLangNameToLangCode.put("Xhosa","xh");
		englishLangNameToLangCode.put("Yakut","sah");
		englishLangNameToLangCode.put("Yao","yao");
		englishLangNameToLangCode.put("Yapese","yap");
		englishLangNameToLangCode.put("Yiddish","yi");
		englishLangNameToLangCode.put("Yoruba","yo");
		englishLangNameToLangCode.put("Zapotec","zap");
		englishLangNameToLangCode.put("Zazaki","zza");
		englishLangNameToLangCode.put("Zenaga","zen");
		englishLangNameToLangCode.put("Zhuang","za");
		englishLangNameToLangCode.put("Zulu","zu");
		englishLangNameToLangCode.put("Zuni","zun");

	}
	
	public static String triletterCode(String s){ 
		if(s!=null && s!="") {
			s= s.trim();
			s=s.toLowerCase();
			String resultat;
			if (ISO639_3.sharedInstance.getIdCode(s) != null) {
				resultat =ISO639_3.sharedInstance.getIdCode(s);
			}else{
				if(englishLangNameToLangCode.containsKey(s)){
					s=englishLangNameToLangCode.get(s);
					
						resultat =ISO639_3.sharedInstance.getIdCode(s);
					
				}else {
					resultat=null;
				}
			}
			return resultat;
		}else{

			return s;
		}
	}

}
