version: '3.3'
services:
    jupyter:
        image: serasset/sparql-jupyterlab:latest
        volumes:
            - ./notebooks:/home/jovyan
        ports:
            - "8888:8888"
        restart: always
