/**
 * 
 */
package org.getalp.dbnary;

import java.util.HashMap;

import org.getalp.blexisma.api.ISO639_3;

/**
 * @author Mariam
 *
 */
public class FrenchLangtoCode {

	static HashMap<String,String> frenchLangNameToLangCode = new HashMap<String,String>();
	static{
		frenchLangNameToLangCode.put("abkhaze","ab");
		frenchLangNameToLangCode.put("achinais","ace");
		frenchLangNameToLangCode.put("acoli","ach");
		frenchLangNameToLangCode.put("adangmé","ada");
		frenchLangNameToLangCode.put("adyghé","ady");
		frenchLangNameToLangCode.put("afar","aa");
		frenchLangNameToLangCode.put("afrihili","afh");
		frenchLangNameToLangCode.put("afrikaans","af");
		frenchLangNameToLangCode.put("aïnou (Japon)","ain");
		frenchLangNameToLangCode.put("akan","ak");
		frenchLangNameToLangCode.put("akkadien","akk");
		frenchLangNameToLangCode.put("albanais","sq");
		frenchLangNameToLangCode.put("alémanique","gsw");
		frenchLangNameToLangCode.put("aléoute","ale");
		frenchLangNameToLangCode.put("allemand","de");
		frenchLangNameToLangCode.put("altaï du Sud","alt");
		frenchLangNameToLangCode.put("amharique","am");
		frenchLangNameToLangCode.put("ancien français","fro");
		frenchLangNameToLangCode.put("ancien occitan","pro");
		frenchLangNameToLangCode.put("angika","anp");
		frenchLangNameToLangCode.put("anglais","en");
		frenchLangNameToLangCode.put("anglo-saxon","ang");
		frenchLangNameToLangCode.put("arabe","ar");
		frenchLangNameToLangCode.put("aragonais","an");
		frenchLangNameToLangCode.put("araméen","arc");
		frenchLangNameToLangCode.put("araméen samaritain","sam");
		frenchLangNameToLangCode.put("arapaho","arp");
		frenchLangNameToLangCode.put("arawak","arw");
		frenchLangNameToLangCode.put("arménien","hy");
		frenchLangNameToLangCode.put("aroumain","rup");
		frenchLangNameToLangCode.put("assamais","as");
		frenchLangNameToLangCode.put("asturien","ast");
		frenchLangNameToLangCode.put("avar","av");
		frenchLangNameToLangCode.put("avestique","ae");
		frenchLangNameToLangCode.put("awadhi","awa");
		frenchLangNameToLangCode.put("aymara","ay");
		frenchLangNameToLangCode.put("azéri","az");
		frenchLangNameToLangCode.put("bachkir","ba");
		frenchLangNameToLangCode.put("balinais","ban");
		frenchLangNameToLangCode.put("baloutche","bal");
		frenchLangNameToLangCode.put("bambara","bm");
		frenchLangNameToLangCode.put("bas allemand","nds");
		frenchLangNameToLangCode.put("bas saxon de Frise orientale","frs");
		frenchLangNameToLangCode.put("basque","eu");
		frenchLangNameToLangCode.put("bassa (Cameroun)","bas");
		frenchLangNameToLangCode.put("bas-sorabe","dsb");
		frenchLangNameToLangCode.put("bedja","bej");
		frenchLangNameToLangCode.put("bemba","bem");
		frenchLangNameToLangCode.put("bengali","bn");
		frenchLangNameToLangCode.put("bhojpuri","bho");
		frenchLangNameToLangCode.put("bichlamar","bi");
		frenchLangNameToLangCode.put("biélorusse","be");
		frenchLangNameToLangCode.put("bikol","bik");
		frenchLangNameToLangCode.put("bilen","byn");
		frenchLangNameToLangCode.put("birman","my");
		frenchLangNameToLangCode.put("bliss","zbl");
		frenchLangNameToLangCode.put("bosniaque","bs");
		frenchLangNameToLangCode.put("bouriate","bua");
		frenchLangNameToLangCode.put("braj","bra");
		frenchLangNameToLangCode.put("breton","br");
		frenchLangNameToLangCode.put("bugis","bug");
		frenchLangNameToLangCode.put("bulgare","bg");
		frenchLangNameToLangCode.put("caddo","cad");
		frenchLangNameToLangCode.put("carélien","krl");
		frenchLangNameToLangCode.put("catalan","ca");
		frenchLangNameToLangCode.put("cébouano","ceb");
		frenchLangNameToLangCode.put("chamorro","ch");
		frenchLangNameToLangCode.put("cherokee","chr");
		frenchLangNameToLangCode.put("cheyenne","chy");
		frenchLangNameToLangCode.put("chinois","zh");
		frenchLangNameToLangCode.put("chipewyan","chp");
		frenchLangNameToLangCode.put("choctaw","cho");
		frenchLangNameToLangCode.put("chuukais","chk");
		frenchLangNameToLangCode.put("cingalais","si");
		frenchLangNameToLangCode.put("copte","cop");
		frenchLangNameToLangCode.put("coréen","ko");
		frenchLangNameToLangCode.put("cornique","kw");
		frenchLangNameToLangCode.put("corse","co");
		frenchLangNameToLangCode.put("cri","cr");
		frenchLangNameToLangCode.put("croate","hr");
		frenchLangNameToLangCode.put("dakota","dak");
		frenchLangNameToLangCode.put("danois","da");
		frenchLangNameToLangCode.put("dargwa","dar");
		frenchLangNameToLangCode.put("dinka","din");
		frenchLangNameToLangCode.put("dioula","dyu");
		frenchLangNameToLangCode.put("divehi","dv");
		frenchLangNameToLangCode.put("dogri","doi");
		frenchLangNameToLangCode.put("douala","dua");
		frenchLangNameToLangCode.put("dzongkha","dz");
		frenchLangNameToLangCode.put("édo","bin");
		frenchLangNameToLangCode.put("éfik","efi");
		frenchLangNameToLangCode.put("égyptien ancien","egy");
		frenchLangNameToLangCode.put("ékadjouk","eka");
		frenchLangNameToLangCode.put("élamite","elx");
		frenchLangNameToLangCode.put("erza","myv");
		frenchLangNameToLangCode.put("esclave","den");
		frenchLangNameToLangCode.put("espagnol","es");
		frenchLangNameToLangCode.put("espéranto","eo");
		frenchLangNameToLangCode.put("estonien","et");
		frenchLangNameToLangCode.put("éwé","ee");
		frenchLangNameToLangCode.put("éwondo","ewo");
		frenchLangNameToLangCode.put("fang","fan");
		frenchLangNameToLangCode.put("fanti","fat");
		frenchLangNameToLangCode.put("féroïen","fo");
		frenchLangNameToLangCode.put("fidjien","fj");
		frenchLangNameToLangCode.put("filipino","fil");
		frenchLangNameToLangCode.put("finnois","fi");
		frenchLangNameToLangCode.put("flanc-de-chien","dgr");
		frenchLangNameToLangCode.put("fon","fon");
		frenchLangNameToLangCode.put("français","fr");
		frenchLangNameToLangCode.put("frioulan","fur");
		frenchLangNameToLangCode.put("frison","fy");
		frenchLangNameToLangCode.put("frison septentrional","frr");
		frenchLangNameToLangCode.put("ga","gaa");
		frenchLangNameToLangCode.put("gaélique écossais","gd");
		frenchLangNameToLangCode.put("gaélique irlandais","ga");
		frenchLangNameToLangCode.put("galicien","gl");
		frenchLangNameToLangCode.put("gallois","cy");
		frenchLangNameToLangCode.put("ganda","lg");
		frenchLangNameToLangCode.put("gayo","gay");
		frenchLangNameToLangCode.put("gbaya","gba");
		frenchLangNameToLangCode.put("géorgien","ka");
		frenchLangNameToLangCode.put("gilbertin","gil");
		frenchLangNameToLangCode.put("gond","gon");
		frenchLangNameToLangCode.put("gorontalo","gor");
		frenchLangNameToLangCode.put("gotique","got");
		frenchLangNameToLangCode.put("goudjarati","gu");
		frenchLangNameToLangCode.put("grébo","grb");
		frenchLangNameToLangCode.put("grec","el");
		frenchLangNameToLangCode.put("grec ancien","grc");
		frenchLangNameToLangCode.put("guarani","gn");
		frenchLangNameToLangCode.put("guèze","gez");
		frenchLangNameToLangCode.put("gwich’in","gwi");
		frenchLangNameToLangCode.put("haïda","hai");
		frenchLangNameToLangCode.put("haïtien","ht");
		frenchLangNameToLangCode.put("haoussa","ha");
		frenchLangNameToLangCode.put("haut-sorabe","hsb");
		frenchLangNameToLangCode.put("hawaïen","haw");
		frenchLangNameToLangCode.put("hébreu","he");
		frenchLangNameToLangCode.put("héréro","hz");
		frenchLangNameToLangCode.put("hiligaynon","hil");
		frenchLangNameToLangCode.put("hindi","hi");
		frenchLangNameToLangCode.put("hiri motou","ho");
		frenchLangNameToLangCode.put("hittite","hit");
		frenchLangNameToLangCode.put("hmong","hmn");
		frenchLangNameToLangCode.put("hongrois","hu");
		frenchLangNameToLangCode.put("hupa","hup");
		frenchLangNameToLangCode.put("iakoute","sah");
		frenchLangNameToLangCode.put("iban","iba");
		frenchLangNameToLangCode.put("ido","io");
		frenchLangNameToLangCode.put("igbo","ig");
		frenchLangNameToLangCode.put("ilocano","ilo");
		frenchLangNameToLangCode.put("indonésien","id");
		frenchLangNameToLangCode.put("ingouche","inh");
		frenchLangNameToLangCode.put("interlingua","ia");
		frenchLangNameToLangCode.put("interlingue","ie");
		frenchLangNameToLangCode.put("inuktitut","iu");
		frenchLangNameToLangCode.put("inupiaq","ik");
		frenchLangNameToLangCode.put("islandais","is");
		frenchLangNameToLangCode.put("italien","it");
		frenchLangNameToLangCode.put("japonais","ja");
		frenchLangNameToLangCode.put("jargon chinook","chn");
		frenchLangNameToLangCode.put("javanais","jv");
		frenchLangNameToLangCode.put("judéo-arabe","jrb");
		frenchLangNameToLangCode.put("judéo-espagnol","lad");
		frenchLangNameToLangCode.put("judéo-persan","jpr");
		frenchLangNameToLangCode.put("kabarde","kbd");
		frenchLangNameToLangCode.put("kabyle","kab");
		frenchLangNameToLangCode.put("kachin","kac");
		frenchLangNameToLangCode.put("kachoube","csb");
		frenchLangNameToLangCode.put("kalaallisut","kl");
		frenchLangNameToLangCode.put("kali’na","car");
		frenchLangNameToLangCode.put("kalmouk","xal");
		frenchLangNameToLangCode.put("kamba","kam");
		frenchLangNameToLangCode.put("kannara","kn");
		frenchLangNameToLangCode.put("kanouri","kr");
		frenchLangNameToLangCode.put("kapampangan","pam");
		frenchLangNameToLangCode.put("karakalpak","kaa");
		frenchLangNameToLangCode.put("karatchaï balkar","krc");
		frenchLangNameToLangCode.put("kashmiri","ks");
		frenchLangNameToLangCode.put("kawi","kaw");
		frenchLangNameToLangCode.put("kazakh","kk");
		frenchLangNameToLangCode.put("khasi","kha");
		frenchLangNameToLangCode.put("khmer","km");
		frenchLangNameToLangCode.put("khotanais","kho");
		frenchLangNameToLangCode.put("kikongo","kg");
		frenchLangNameToLangCode.put("kikuyu","ki");
		frenchLangNameToLangCode.put("kimboundou","kmb");
		frenchLangNameToLangCode.put("kinyarwanda","rw");
		frenchLangNameToLangCode.put("kirghiz","ky");
		frenchLangNameToLangCode.put("kirundi","rn");
		frenchLangNameToLangCode.put("klingon","tlh");
		frenchLangNameToLangCode.put("komi","kv");
		frenchLangNameToLangCode.put("konkânî","kok");
		frenchLangNameToLangCode.put("kosraéen","kos");
		frenchLangNameToLangCode.put("koumyk","kum");
		frenchLangNameToLangCode.put("kpellé","kpe");
		frenchLangNameToLangCode.put("kuanyama","kj");
		frenchLangNameToLangCode.put("kurde","ku");
		frenchLangNameToLangCode.put("kurukh","kru");
		frenchLangNameToLangCode.put("kutenai","kut");
		frenchLangNameToLangCode.put("lahnda","lah");
		frenchLangNameToLangCode.put("lamba","lam");
		frenchLangNameToLangCode.put("laotien","lo");
		frenchLangNameToLangCode.put("latin","la");
		frenchLangNameToLangCode.put("lenape","del");
		frenchLangNameToLangCode.put("letton","lv");
		frenchLangNameToLangCode.put("lezghien","lez");
		frenchLangNameToLangCode.put("limbourgeois","li");
		frenchLangNameToLangCode.put("lingala","ln");
		frenchLangNameToLangCode.put("lituanien","lt");
		frenchLangNameToLangCode.put("lojban","jbo");
		frenchLangNameToLangCode.put("lomongo","lol");
		frenchLangNameToLangCode.put("louba-katanga","lu");
		frenchLangNameToLangCode.put("lounda","lun");
		frenchLangNameToLangCode.put("lozi","loz");
		frenchLangNameToLangCode.put("luba-lulua","lua");
		frenchLangNameToLangCode.put("luiseño","lui");
		frenchLangNameToLangCode.put("luo (Kenya, Tanzanie)","luo");
		frenchLangNameToLangCode.put("luxembourgeois","lb");
		frenchLangNameToLangCode.put("macédonien","mk");
		frenchLangNameToLangCode.put("madourais","mad");
		frenchLangNameToLangCode.put("magahi","mag");
		frenchLangNameToLangCode.put("maithili","mai");
		frenchLangNameToLangCode.put("makassar","mak");
		frenchLangNameToLangCode.put("malais","ms");
		frenchLangNameToLangCode.put("malayalam","ml");
		frenchLangNameToLangCode.put("malgache","mg");
		frenchLangNameToLangCode.put("maltais","mt");
		frenchLangNameToLangCode.put("mandar","mdr");
		frenchLangNameToLangCode.put("mandchou","mnc");
		frenchLangNameToLangCode.put("mandingue","man");
		frenchLangNameToLangCode.put("manipourî","mni");
		frenchLangNameToLangCode.put("mannois","gv");
		frenchLangNameToLangCode.put("maori","mi");
		frenchLangNameToLangCode.put("mapuche","arn");
		frenchLangNameToLangCode.put("marathe","mr");
		frenchLangNameToLangCode.put("mari","chm");
		frenchLangNameToLangCode.put("marshallais","mh");
		frenchLangNameToLangCode.put("marvari","mwr");
		frenchLangNameToLangCode.put("massaï","mas");
		frenchLangNameToLangCode.put("mendé","men");
		frenchLangNameToLangCode.put("micmac","mic");
		frenchLangNameToLangCode.put("minangkabau","min");
		frenchLangNameToLangCode.put("mirandais","mwl");
		frenchLangNameToLangCode.put("mizo","lus");
		frenchLangNameToLangCode.put("mohawk","moh");
		frenchLangNameToLangCode.put("mokcha","mdf");
		frenchLangNameToLangCode.put("moldave","mo");
		frenchLangNameToLangCode.put("mongol","mn");
		frenchLangNameToLangCode.put("moré","mos");
		frenchLangNameToLangCode.put("moyen anglais","enm");
		frenchLangNameToLangCode.put("moyen français","frm");
		frenchLangNameToLangCode.put("moyen haut-allemand","gmh");
		frenchLangNameToLangCode.put("moyen irlandais","mga");
		frenchLangNameToLangCode.put("moyen néerlandais","dum");
		frenchLangNameToLangCode.put("muisca","chb");
		frenchLangNameToLangCode.put("muskogee","mus");
		frenchLangNameToLangCode.put("n’ko","nqo");
		frenchLangNameToLangCode.put("napolitain","nap");
		frenchLangNameToLangCode.put("nauruan","na");
		frenchLangNameToLangCode.put("navajo","nv");
		frenchLangNameToLangCode.put("ndébélé du Nord","nd");
		frenchLangNameToLangCode.put("ndébélé du Sud","nr");
		frenchLangNameToLangCode.put("ndonga","ng");
		frenchLangNameToLangCode.put("néerlandais","nl");
		frenchLangNameToLangCode.put("népalais","ne");
		frenchLangNameToLangCode.put("newari","new");
		frenchLangNameToLangCode.put("newari classique","nwc");
		frenchLangNameToLangCode.put("nias","nia");
		frenchLangNameToLangCode.put("niuéen","niu");
		frenchLangNameToLangCode.put("nogaï","nog");
		frenchLangNameToLangCode.put("norvégien","no");
		frenchLangNameToLangCode.put("norvégien (bokmål)","nb");
		frenchLangNameToLangCode.put("norvégien (nynorsk)","nn");
		frenchLangNameToLangCode.put("nyamwezi","nym");
		frenchLangNameToLangCode.put("nyanja","ny");
		frenchLangNameToLangCode.put("nyankolé","nyn");
		frenchLangNameToLangCode.put("nyoro","nyo");
		frenchLangNameToLangCode.put("nzéma","nzi");
		frenchLangNameToLangCode.put("occitan","oc");
		frenchLangNameToLangCode.put("ojibwa","oj");
		frenchLangNameToLangCode.put("oriya","or");
		frenchLangNameToLangCode.put("oromo","om");
		frenchLangNameToLangCode.put("osage","osa");
		frenchLangNameToLangCode.put("ossète","os");
		frenchLangNameToLangCode.put("oudmourte","udm");
		frenchLangNameToLangCode.put("ougaritique","uga");
		frenchLangNameToLangCode.put("ouïghour","ug");
		frenchLangNameToLangCode.put("oumboundou","umb");
		frenchLangNameToLangCode.put("ourdou","ur");
		frenchLangNameToLangCode.put("ouzbek","uz");
		frenchLangNameToLangCode.put("pachto","ps");
		frenchLangNameToLangCode.put("palau","pau");
		frenchLangNameToLangCode.put("pali","pi");
		frenchLangNameToLangCode.put("pangasinan","pag");
		frenchLangNameToLangCode.put("papiamento","pap");
		frenchLangNameToLangCode.put("pehlevi","pal");
		frenchLangNameToLangCode.put("pendjabi","pa");
		frenchLangNameToLangCode.put("persan","fa");
		frenchLangNameToLangCode.put("peul","ff");
		frenchLangNameToLangCode.put("phénicien","phn");
		frenchLangNameToLangCode.put("pied-noir","bla");
		frenchLangNameToLangCode.put("pohnpei","pon");
		frenchLangNameToLangCode.put("polonais","pl");
		frenchLangNameToLangCode.put("portugais","pt");
		frenchLangNameToLangCode.put("quechua","qu");
		frenchLangNameToLangCode.put("rajasthani","raj");
		frenchLangNameToLangCode.put("rapanui","rap");
		frenchLangNameToLangCode.put("rarotongien","rar");
		frenchLangNameToLangCode.put("romanche","rm");
		frenchLangNameToLangCode.put("romani","rom");
		frenchLangNameToLangCode.put("roumain","ro");
		frenchLangNameToLangCode.put("russe","ru");
		frenchLangNameToLangCode.put("same d’Inari","smn");
		frenchLangNameToLangCode.put("same de Lule","smj");
		frenchLangNameToLangCode.put("same du Nord","se");
		frenchLangNameToLangCode.put("same du Sud","sma");
		frenchLangNameToLangCode.put("same skolt","sms");
		frenchLangNameToLangCode.put("samoan","sm");
		frenchLangNameToLangCode.put("sandawé","sad");
		frenchLangNameToLangCode.put("sango","sg");
		frenchLangNameToLangCode.put("sans contenu linguistique","zxx");
		frenchLangNameToLangCode.put("sanskrit","sa");
		frenchLangNameToLangCode.put("santal","sat");
		frenchLangNameToLangCode.put("sarde","sc");
		frenchLangNameToLangCode.put("sassak","sas");
		frenchLangNameToLangCode.put("scots","sco");
		frenchLangNameToLangCode.put("selkoupe","sel");
		frenchLangNameToLangCode.put("serbe","sr");
		frenchLangNameToLangCode.put("serbo-croate","sh");
		frenchLangNameToLangCode.put("sérère","srr");
		frenchLangNameToLangCode.put("shan","shn");
		frenchLangNameToLangCode.put("shona","sn");
		frenchLangNameToLangCode.put("sicilien","scn");
		frenchLangNameToLangCode.put("sidamo","sid");
		frenchLangNameToLangCode.put("sindhi","sd");
		frenchLangNameToLangCode.put("slovaque","sk");
		frenchLangNameToLangCode.put("slovène","sl");
		frenchLangNameToLangCode.put("sogdien","sog");
		frenchLangNameToLangCode.put("somali","so");
		frenchLangNameToLangCode.put("soninké","snk");
		frenchLangNameToLangCode.put("sotho du Nord","nso");
		frenchLangNameToLangCode.put("sotho du Sud","st");
		frenchLangNameToLangCode.put("soukouma","suk");
		frenchLangNameToLangCode.put("soundanais","su");
		frenchLangNameToLangCode.put("soussou","sus");
		frenchLangNameToLangCode.put("sranan","srn");
		frenchLangNameToLangCode.put("suédois","sv");
		frenchLangNameToLangCode.put("sumérien","sux");
		frenchLangNameToLangCode.put("swahili","sw");
		frenchLangNameToLangCode.put("swazi","ss");
		frenchLangNameToLangCode.put("syriaque","syr");
		frenchLangNameToLangCode.put("syriaque classique","syc");
		frenchLangNameToLangCode.put("tadjik","tg");
		frenchLangNameToLangCode.put("tagalog","tl");
		frenchLangNameToLangCode.put("tahitien","ty");
		frenchLangNameToLangCode.put("tamasheq (macrolangue)","tmh");
		frenchLangNameToLangCode.put("tamoul","ta");
		frenchLangNameToLangCode.put("tatar de Crimée","crh");
		frenchLangNameToLangCode.put("tatare","tt");
		frenchLangNameToLangCode.put("tchaghataï","chg");
		frenchLangNameToLangCode.put("tchèque","cs");
		frenchLangNameToLangCode.put("tchétchène","ce");
		frenchLangNameToLangCode.put("tchouvache","cv");
		frenchLangNameToLangCode.put("télougou","te");
		frenchLangNameToLangCode.put("temné","tem");
		frenchLangNameToLangCode.put("téréno","ter");
		frenchLangNameToLangCode.put("tétoum","tet");
		frenchLangNameToLangCode.put("thaï","th");
		frenchLangNameToLangCode.put("tibétain","bo");
		frenchLangNameToLangCode.put("tigré","tig");
		frenchLangNameToLangCode.put("tigrigna","ti");
		frenchLangNameToLangCode.put("tiv","tiv");
		frenchLangNameToLangCode.put("tlingit","tli");
		frenchLangNameToLangCode.put("tok pisin","tpi");
		frenchLangNameToLangCode.put("tokelauien","tkl");
		frenchLangNameToLangCode.put("tonga","tog");
		frenchLangNameToLangCode.put("tongien","to");
		frenchLangNameToLangCode.put("touvain","tyv");
		frenchLangNameToLangCode.put("tsimshian","tsi");
		frenchLangNameToLangCode.put("tsonga","ts");
		frenchLangNameToLangCode.put("tswana","tn");
		frenchLangNameToLangCode.put("tumbuka","tum");
		frenchLangNameToLangCode.put("turc","tr");
		frenchLangNameToLangCode.put("turc ottoman","ota");
		frenchLangNameToLangCode.put("turkmène","tk");
		frenchLangNameToLangCode.put("tuvalu","tvl");
		frenchLangNameToLangCode.put("twi","tw");
		frenchLangNameToLangCode.put("ukrainien","uk");
		frenchLangNameToLangCode.put("vaï","vai");
		frenchLangNameToLangCode.put("venda","ve");
		frenchLangNameToLangCode.put("vieil irlandais","sga");
		frenchLangNameToLangCode.put("vietnamien","vi");
		frenchLangNameToLangCode.put("vieux haut allemand","goh");
		frenchLangNameToLangCode.put("vieux norrois","non");
		frenchLangNameToLangCode.put("vieux slave","cu");
		frenchLangNameToLangCode.put("vieux-perse","peo");
		frenchLangNameToLangCode.put("volapük","vo");
		frenchLangNameToLangCode.put("vote","vot");
		frenchLangNameToLangCode.put("wallon","wa");
		frenchLangNameToLangCode.put("waray","war");
		frenchLangNameToLangCode.put("washo","was");
		frenchLangNameToLangCode.put("wolaytta","wal");
		frenchLangNameToLangCode.put("wolof","wo");
		frenchLangNameToLangCode.put("xhosa","xh");
		frenchLangNameToLangCode.put("yao","yao");
		frenchLangNameToLangCode.put("yapois","yap");
		frenchLangNameToLangCode.put("yi","ii");
		frenchLangNameToLangCode.put("yiddish","yi");
		frenchLangNameToLangCode.put("yoruba","yo");
		frenchLangNameToLangCode.put("zapotèque","zap");
		frenchLangNameToLangCode.put("zazaki","zza");
		frenchLangNameToLangCode.put("zénaga","zen");
		frenchLangNameToLangCode.put("zhuang","za");
		frenchLangNameToLangCode.put("zoulou","zu");
		frenchLangNameToLangCode.put("zuni","zun");


	}

	public static String triletterCode(String s){ 
		if(s!=null && s!="") {
			s= s.trim();
			s=s.toLowerCase();
			String resultat;
			if (ISO639_3.sharedInstance.getIdCode(s) != null) {
				resultat =ISO639_3.sharedInstance.getIdCode(s);
			}else{
				if(frenchLangNameToLangCode.containsKey(s)){
					s=frenchLangNameToLangCode.get(s);
					
						resultat =ISO639_3.sharedInstance.getIdCode(s);
					
				}else {
					resultat=null;
				}
			}
			return resultat;
		}else{

			return s;
		}
	}

}
