/**
 * 
 */
package org.getalp.dbnary;

import java.util.HashMap;

import org.getalp.blexisma.api.ISO639_3;

/**
 * @author Mariam
 *
 */
public class PortugueseLangToCode {


	static HashMap<String,String> portugueseLangNameToLangCode = new HashMap<String,String>();
	static{
		portugueseLangNameToLangCode.put("Abecásio","ab");
		portugueseLangNameToLangCode.put("Acadiano","akk");
		portugueseLangNameToLangCode.put("Acenês","ace");
		portugueseLangNameToLangCode.put("Afar","aa");
		portugueseLangNameToLangCode.put("Africâner","af");
		portugueseLangNameToLangCode.put("Aimará","ay");
		portugueseLangNameToLangCode.put("Aino","ain");
		portugueseLangNameToLangCode.put("Akan","ak");
		portugueseLangNameToLangCode.put("Albanês","sq");
		portugueseLangNameToLangCode.put("Alemânico","gsw");
		portugueseLangNameToLangCode.put("Alemão","de");
		portugueseLangNameToLangCode.put("Aleúte","ale");
		portugueseLangNameToLangCode.put("Altaico","alt");
		portugueseLangNameToLangCode.put("Alto Alemão Antigo","goh");
		portugueseLangNameToLangCode.put("Alto Alemão Médio","gmh");
		portugueseLangNameToLangCode.put("Amárico","am");
		portugueseLangNameToLangCode.put("Árabe","ar");
		portugueseLangNameToLangCode.put("Aragonês","an");
		portugueseLangNameToLangCode.put("Aramaico","arc");
		portugueseLangNameToLangCode.put("Arapaho","arp");
		portugueseLangNameToLangCode.put("Araucano","arn");
		portugueseLangNameToLangCode.put("Armênio","hy");
		portugueseLangNameToLangCode.put("Aromeno","rup");
		portugueseLangNameToLangCode.put("Aruaque","arw");
		portugueseLangNameToLangCode.put("Assamês","as");
		portugueseLangNameToLangCode.put("Asturiano","ast");
		portugueseLangNameToLangCode.put("Avárico","av");
		portugueseLangNameToLangCode.put("Avéstico","ae");
		portugueseLangNameToLangCode.put("Azerbaijano","az");
		portugueseLangNameToLangCode.put("Baixo Saxão","nds");
		portugueseLangNameToLangCode.put("Balinês","ban");
		portugueseLangNameToLangCode.put("Balúchi","bal");
		portugueseLangNameToLangCode.put("Bambara","bm");
		portugueseLangNameToLangCode.put("Basa","bas");
		portugueseLangNameToLangCode.put("Basco","eu");
		portugueseLangNameToLangCode.put("Basquir","ba");
		portugueseLangNameToLangCode.put("Bemba","bem");
		portugueseLangNameToLangCode.put("Bengali","bn");
		portugueseLangNameToLangCode.put("Bhojpuri","bho");
		portugueseLangNameToLangCode.put("Bicolano","bik");
		portugueseLangNameToLangCode.put("Bielorrusso","be");
		portugueseLangNameToLangCode.put("Birmanês","my");
		portugueseLangNameToLangCode.put("Bislamá","bi");
		portugueseLangNameToLangCode.put("Bósnio","bs");
		portugueseLangNameToLangCode.put("Bretão","br");
		portugueseLangNameToLangCode.put("Buginês","bug");
		portugueseLangNameToLangCode.put("Búlgaro","bg");
		portugueseLangNameToLangCode.put("Buriate","bua");
		portugueseLangNameToLangCode.put("Cabardino","kbd");
		portugueseLangNameToLangCode.put("Cabila","kab");
		portugueseLangNameToLangCode.put("Cachúbio","csb");
		portugueseLangNameToLangCode.put("Caddo","cad");
		portugueseLangNameToLangCode.put("Calmuco","xal");
		portugueseLangNameToLangCode.put("Cambojano","km");
		portugueseLangNameToLangCode.put("Canarês","kn");
		portugueseLangNameToLangCode.put("Caracalpaque","kaa");
		portugueseLangNameToLangCode.put("Carachai-Balcar","krc");
		portugueseLangNameToLangCode.put("Carélio","krl");
		portugueseLangNameToLangCode.put("Catalão","ca");
		portugueseLangNameToLangCode.put("Caxemira","ks");
		portugueseLangNameToLangCode.put("Cazaque","kk");
		portugueseLangNameToLangCode.put("Cebuano","ceb");
		portugueseLangNameToLangCode.put("Chagatai","chg");
		portugueseLangNameToLangCode.put("Chamorro","ch");
		portugueseLangNameToLangCode.put("Checheno","ce");
		portugueseLangNameToLangCode.put("Checo","cs");
		portugueseLangNameToLangCode.put("Cherokee","chr");
		portugueseLangNameToLangCode.put("Cheyenne","chy");
		portugueseLangNameToLangCode.put("Chibcha/Muisca","chb");
		portugueseLangNameToLangCode.put("Chinês","zh");
		portugueseLangNameToLangCode.put("Chipewyan","chp");
		portugueseLangNameToLangCode.put("Choctaw","cho");
		portugueseLangNameToLangCode.put("Chona","sn");
		portugueseLangNameToLangCode.put("Cingalês","si");
		portugueseLangNameToLangCode.put("Circassiano","ady");
		portugueseLangNameToLangCode.put("Concani","kok");
		portugueseLangNameToLangCode.put("Copta","cop");
		portugueseLangNameToLangCode.put("Coreano","ko");
		portugueseLangNameToLangCode.put("Córnico","kw");
		portugueseLangNameToLangCode.put("Corso","co");
		portugueseLangNameToLangCode.put("Cree","cr");
		portugueseLangNameToLangCode.put("Creek","mus");
		portugueseLangNameToLangCode.put("Croata","hr");
		portugueseLangNameToLangCode.put("Cuanhama","kj");
		portugueseLangNameToLangCode.put("Curdo","ku");
		portugueseLangNameToLangCode.put("Dakota","dak");
		portugueseLangNameToLangCode.put("Dano-norueguês","nb");
		portugueseLangNameToLangCode.put("Dargínico","dar");
		portugueseLangNameToLangCode.put("Delaware","del");
		portugueseLangNameToLangCode.put("Dinamarquês","da");
		portugueseLangNameToLangCode.put("Divehi","dv");
		portugueseLangNameToLangCode.put("Duala","dua");
		portugueseLangNameToLangCode.put("Egípcio","egy");
		portugueseLangNameToLangCode.put("Elamita","elx");
		portugueseLangNameToLangCode.put("Erzya","myv");
		portugueseLangNameToLangCode.put("Escocês","sco");
		portugueseLangNameToLangCode.put("Eslavo Eclesiástico","cu");
		portugueseLangNameToLangCode.put("Eslovaco","sk");
		portugueseLangNameToLangCode.put("Esloveno","sl");
		portugueseLangNameToLangCode.put("Espanhol","es");
		portugueseLangNameToLangCode.put("Esperanto","eo");
		portugueseLangNameToLangCode.put("Estoniano","et");
		portugueseLangNameToLangCode.put("Fenício","phn");
		portugueseLangNameToLangCode.put("Feroês","fo");
		portugueseLangNameToLangCode.put("Fijiano","fj");
		portugueseLangNameToLangCode.put("Filipino","fil");
		portugueseLangNameToLangCode.put("Finlandês","fi");
		portugueseLangNameToLangCode.put("Francês","fr");
		portugueseLangNameToLangCode.put("Francês Antigo","fro");
		portugueseLangNameToLangCode.put("Francês Médio","frm");
		portugueseLangNameToLangCode.put("Frísio","fy");
		portugueseLangNameToLangCode.put("Frísio Setentrional","frr");
		portugueseLangNameToLangCode.put("Friuliano","fur");
		portugueseLangNameToLangCode.put("Fula","ff");
		portugueseLangNameToLangCode.put("Ga","gaa");
		portugueseLangNameToLangCode.put("Gaélico Escocês","gd");
		portugueseLangNameToLangCode.put("Galego","gl");
		portugueseLangNameToLangCode.put("Galês","cy");
		portugueseLangNameToLangCode.put("Gayo","gay");
		portugueseLangNameToLangCode.put("Ge'ez","gez");
		portugueseLangNameToLangCode.put("Georgiano","ka");
		portugueseLangNameToLangCode.put("Gilbertês","gil");
		portugueseLangNameToLangCode.put("Gótico","got");
		portugueseLangNameToLangCode.put("Grego","el");
		portugueseLangNameToLangCode.put("Grego Antigo","grc");
		portugueseLangNameToLangCode.put("Groenlandês","kl");
		portugueseLangNameToLangCode.put("Guarani","gn");
		portugueseLangNameToLangCode.put("Guzerate","gu");
		portugueseLangNameToLangCode.put("Haida","hai");
		portugueseLangNameToLangCode.put("Haitiano","ht");
		portugueseLangNameToLangCode.put("Hauçá","ha");
		portugueseLangNameToLangCode.put("Havaiano","haw");
		portugueseLangNameToLangCode.put("Hebraico","he");
		portugueseLangNameToLangCode.put("Hereró","hz");
		portugueseLangNameToLangCode.put("Hiligaynon","hil");
		portugueseLangNameToLangCode.put("Hindi","hi");
		portugueseLangNameToLangCode.put("Hiri Motu","ho");
		portugueseLangNameToLangCode.put("Hitita","hit");
		portugueseLangNameToLangCode.put("Hmong","hmn");
		portugueseLangNameToLangCode.put("Holandês","nl");
		portugueseLangNameToLangCode.put("Holandês Médio","dum");
		portugueseLangNameToLangCode.put("Húngaro","hu");
		portugueseLangNameToLangCode.put("Iacute","sah");
		portugueseLangNameToLangCode.put("Iban","iba");
		portugueseLangNameToLangCode.put("Ibo","ig");
		portugueseLangNameToLangCode.put("Ido","io");
		portugueseLangNameToLangCode.put("Iídiche","yi");
		portugueseLangNameToLangCode.put("Ilocano","ilo");
		portugueseLangNameToLangCode.put("Indonésio","id");
		portugueseLangNameToLangCode.put("Inglês","en");
		portugueseLangNameToLangCode.put("Inglês Antigo","ang");
		portugueseLangNameToLangCode.put("Inglês Médio","enm");
		portugueseLangNameToLangCode.put("Inguche","inh");
		portugueseLangNameToLangCode.put("Interlíngua","ia");
		portugueseLangNameToLangCode.put("Interlíngue","ie");
		portugueseLangNameToLangCode.put("Inuktitut","iu");
		portugueseLangNameToLangCode.put("Inupiaque","ik");
		portugueseLangNameToLangCode.put("Iorubá","yo");
		portugueseLangNameToLangCode.put("Irlandês","ga");
		portugueseLangNameToLangCode.put("Irlandês Antigo","sga");
		portugueseLangNameToLangCode.put("Islandês","is");
		portugueseLangNameToLangCode.put("Italiano","it");
		portugueseLangNameToLangCode.put("Japonês","ja");
		portugueseLangNameToLangCode.put("Javanês","jv");
		portugueseLangNameToLangCode.put("Jeje","ee");
		portugueseLangNameToLangCode.put("Jingpo","kac");
		portugueseLangNameToLangCode.put("Kamba","kam");
		portugueseLangNameToLangCode.put("Kanuri","kr");
		portugueseLangNameToLangCode.put("Khasi","kha");
		portugueseLangNameToLangCode.put("Khotanês","kho");
		portugueseLangNameToLangCode.put("Kikongo","kg");
		portugueseLangNameToLangCode.put("Kikuyo","ki");
		portugueseLangNameToLangCode.put("Klingon","tlh");
		portugueseLangNameToLangCode.put("Komi","kv");
		portugueseLangNameToLangCode.put("Kosraeano","kos");
		portugueseLangNameToLangCode.put("Kumyk","kum");
		portugueseLangNameToLangCode.put("Ladino","lad");
		portugueseLangNameToLangCode.put("Laociano","lo");
		portugueseLangNameToLangCode.put("Latim","la");
		portugueseLangNameToLangCode.put("Letão","lv");
		portugueseLangNameToLangCode.put("Lezguiano","lez");
		portugueseLangNameToLangCode.put("Limburguês","li");
		portugueseLangNameToLangCode.put("Lingala","ln");
		portugueseLangNameToLangCode.put("Lituano","lt");
		portugueseLangNameToLangCode.put("Lojban","jbo");
		portugueseLangNameToLangCode.put("Luganda","lg");
		portugueseLangNameToLangCode.put("Luo","luo");
		portugueseLangNameToLangCode.put("Lushai","lus");
		portugueseLangNameToLangCode.put("Luxemburguês","lb");
		portugueseLangNameToLangCode.put("Macedônio","mk");
		portugueseLangNameToLangCode.put("Madurês","mad");
		portugueseLangNameToLangCode.put("Makasar","mak");
		portugueseLangNameToLangCode.put("Malaiala","ml");
		portugueseLangNameToLangCode.put("Malaio","ms");
		portugueseLangNameToLangCode.put("Malgaxe","mg");
		portugueseLangNameToLangCode.put("Maltês","mt");
		portugueseLangNameToLangCode.put("Manchu","mnc");
		portugueseLangNameToLangCode.put("Manipuri","mni");
		portugueseLangNameToLangCode.put("Manquês","gv");
		portugueseLangNameToLangCode.put("Maori","mi");
		portugueseLangNameToLangCode.put("Marati","mr");
		portugueseLangNameToLangCode.put("Mari","chm");
		portugueseLangNameToLangCode.put("Marshalês","mh");
		portugueseLangNameToLangCode.put("Massai","mas");
		portugueseLangNameToLangCode.put("Micmac","mic");
		portugueseLangNameToLangCode.put("Minangkabau","min");
		portugueseLangNameToLangCode.put("Mirandês","mwl");
		portugueseLangNameToLangCode.put("Mohawk","moh");
		portugueseLangNameToLangCode.put("Moksha","mdf");
		portugueseLangNameToLangCode.put("Moldavo","mo");
		portugueseLangNameToLangCode.put("Mongol","mn");
		portugueseLangNameToLangCode.put("Napolitano","nap");
		portugueseLangNameToLangCode.put("Nauruano","na");
		portugueseLangNameToLangCode.put("Navajo","nv");
		portugueseLangNameToLangCode.put("Ndebele Meridional","nr");
		portugueseLangNameToLangCode.put("Ndebele Setentrional","nd");
		portugueseLangNameToLangCode.put("Ndonga","ng");
		portugueseLangNameToLangCode.put("Nepalês","ne");
		portugueseLangNameToLangCode.put("Newari","new");
		portugueseLangNameToLangCode.put("Nias","nia");
		portugueseLangNameToLangCode.put("Niue","niu");
		portugueseLangNameToLangCode.put("Nogai","nog");
		portugueseLangNameToLangCode.put("Nórdico Antigo","non");
		portugueseLangNameToLangCode.put("Norueguês","no");
		portugueseLangNameToLangCode.put("Novo Norueguês","nn");
		portugueseLangNameToLangCode.put("Nyamwezi","nym");
		portugueseLangNameToLangCode.put("Nyanja","ny");
		portugueseLangNameToLangCode.put("Occitano","oc");
		portugueseLangNameToLangCode.put("Ojibua","oj");
		portugueseLangNameToLangCode.put("Oriá","or");
		portugueseLangNameToLangCode.put("Oromo","om");
		portugueseLangNameToLangCode.put("Osseta","os");
		portugueseLangNameToLangCode.put("Palauano","pau");
		portugueseLangNameToLangCode.put("Pali","pi");
		portugueseLangNameToLangCode.put("Pampangan","pam");
		portugueseLangNameToLangCode.put("Pangasinan","pag");
		portugueseLangNameToLangCode.put("Papiamento","pap");
		portugueseLangNameToLangCode.put("Pashtu","ps");
		portugueseLangNameToLangCode.put("Persa","fa");
		portugueseLangNameToLangCode.put("Persa Antigo","peo");
		portugueseLangNameToLangCode.put("Pohnpeiano","pon");
		portugueseLangNameToLangCode.put("Polonês","pl");
		portugueseLangNameToLangCode.put("Português","pt");
		portugueseLangNameToLangCode.put("Provençal Antigo","pro");
		portugueseLangNameToLangCode.put("Punjabi","pa");
		portugueseLangNameToLangCode.put("Quéchua","qu");
		portugueseLangNameToLangCode.put("Quimbundo","kmb");
		portugueseLangNameToLangCode.put("Quirguiz","ky");
		portugueseLangNameToLangCode.put("Rajastani","raj");
		portugueseLangNameToLangCode.put("Rapanui","rap");
		portugueseLangNameToLangCode.put("Rarotonga","rar");
		portugueseLangNameToLangCode.put("Romanche","rm");
		portugueseLangNameToLangCode.put("Romani","rom");
		portugueseLangNameToLangCode.put("Romeno","ro");
		portugueseLangNameToLangCode.put("Ruanda","rw");
		portugueseLangNameToLangCode.put("Rundi","rn");
		portugueseLangNameToLangCode.put("Russo","ru");
		portugueseLangNameToLangCode.put("Sami Inari","smn");
		portugueseLangNameToLangCode.put("Sami Lule","smj");
		portugueseLangNameToLangCode.put("Sami Meridional","sma");
		portugueseLangNameToLangCode.put("Sami Setentrional","se");
		portugueseLangNameToLangCode.put("Sami Skolt","sms");
		portugueseLangNameToLangCode.put("Samoano","sm");
		portugueseLangNameToLangCode.put("Sango","sg");
		portugueseLangNameToLangCode.put("Sânscrito","sa");
		portugueseLangNameToLangCode.put("Santali","sat");
		portugueseLangNameToLangCode.put("Sardo","sc");
		portugueseLangNameToLangCode.put("Sasaque","sas");
		portugueseLangNameToLangCode.put("Sepédi","nso");
		portugueseLangNameToLangCode.put("Sérvio","sr");
		portugueseLangNameToLangCode.put("Servocroata","sh");
		portugueseLangNameToLangCode.put("Sesoto","st");
		portugueseLangNameToLangCode.put("Shan","shn");
		portugueseLangNameToLangCode.put("Siciliano","scn");
		portugueseLangNameToLangCode.put("Siksika","bla");
		portugueseLangNameToLangCode.put("Sindi","sd");
		portugueseLangNameToLangCode.put("Siríaco","syr");
		portugueseLangNameToLangCode.put("Sogdiano","sog");
		portugueseLangNameToLangCode.put("Somali","so");
		portugueseLangNameToLangCode.put("Sorábio Alto","hsb");
		portugueseLangNameToLangCode.put("Sorábio Baixo","dsb");
		portugueseLangNameToLangCode.put("Suaíli","sw");
		portugueseLangNameToLangCode.put("Suazi","ss");
		portugueseLangNameToLangCode.put("Sueco","sv");
		portugueseLangNameToLangCode.put("Sumério","sux");
		portugueseLangNameToLangCode.put("Sundanês","su");
		portugueseLangNameToLangCode.put("Surinamês","srn");
		portugueseLangNameToLangCode.put("Tadjique","tg");
		portugueseLangNameToLangCode.put("Tagalo","tl");
		portugueseLangNameToLangCode.put("Tailandês","th");
		portugueseLangNameToLangCode.put("Taitiano","ty");
		portugueseLangNameToLangCode.put("Tâmil","ta");
		portugueseLangNameToLangCode.put("Tártaro","tt");
		portugueseLangNameToLangCode.put("Tártaro da Crimeia","crh");
		portugueseLangNameToLangCode.put("Tchuvache","cv");
		portugueseLangNameToLangCode.put("Télugo","te");
		portugueseLangNameToLangCode.put("Tétum","tet");
		portugueseLangNameToLangCode.put("Tibetano","bo");
		portugueseLangNameToLangCode.put("Tigré","tig");
		portugueseLangNameToLangCode.put("Tigrina","ti");
		portugueseLangNameToLangCode.put("Tlingit","tli");
		portugueseLangNameToLangCode.put("Tok Pisin","tpi");
		portugueseLangNameToLangCode.put("Tonganês","to");
		portugueseLangNameToLangCode.put("Toquelau","tkl");
		portugueseLangNameToLangCode.put("Truquês","chk");
		portugueseLangNameToLangCode.put("Tsonga","ts");
		portugueseLangNameToLangCode.put("Tswana","tn");
		portugueseLangNameToLangCode.put("Tumbuca","tum");
		portugueseLangNameToLangCode.put("Turco","tr");
		portugueseLangNameToLangCode.put("Turco Otomano","ota");
		portugueseLangNameToLangCode.put("Turcomeno","tk");
		portugueseLangNameToLangCode.put("Tuvaluano","tvl");
		portugueseLangNameToLangCode.put("Tuvano","tyv");
		portugueseLangNameToLangCode.put("Twi","tw");
		portugueseLangNameToLangCode.put("Ucraniano","uk");
		portugueseLangNameToLangCode.put("Ugarítico","uga");
		portugueseLangNameToLangCode.put("Uigure","ug");
		portugueseLangNameToLangCode.put("Umbundo","umb");
		portugueseLangNameToLangCode.put("Uolofe","wo");
		portugueseLangNameToLangCode.put("Urdu","ur");
		portugueseLangNameToLangCode.put("Uzbeque","uz");
		portugueseLangNameToLangCode.put("Valão","wa");
		portugueseLangNameToLangCode.put("Venda","ve");
		portugueseLangNameToLangCode.put("Vietnamita","vi");
		portugueseLangNameToLangCode.put("Volapuque","vo");
		portugueseLangNameToLangCode.put("Votíaco","udm");
		portugueseLangNameToLangCode.put("Voto","vot");
		portugueseLangNameToLangCode.put("Waray-Waray","war");
		portugueseLangNameToLangCode.put("Xhosa","xh");
		portugueseLangNameToLangCode.put("Yao","yao");
		portugueseLangNameToLangCode.put("Yapês","yap");
		portugueseLangNameToLangCode.put("Yi","ii");
		portugueseLangNameToLangCode.put("Zapoteca","zap");
		portugueseLangNameToLangCode.put("Zhuang","za");
		portugueseLangNameToLangCode.put("Zoncá","dz");
		portugueseLangNameToLangCode.put("Zulu","zu");
		portugueseLangNameToLangCode.put("Zuni","zun");

	}

	public static String triletterCode(String s){ 
		if(s!=null && s!="") {
			s= s.trim();
			
			String resultat;
			if (ISO639_3.sharedInstance.getIdCode(s) != null) {
				resultat =ISO639_3.sharedInstance.getIdCode(s);
			}else{
				if(portugueseLangNameToLangCode.containsKey(s)){
					s=portugueseLangNameToLangCode.get(s);
					
						resultat =ISO639_3.sharedInstance.getIdCode(s);
					
				}else {
					resultat=s;
				}
			}
			return resultat;
		}else{

			return s;
		}
	}
}
