package org.getalp.dbnary.cli;

import java.io.IOException;
import java.time.Duration;
import java.util.function.BiConsumer;
import javax.xml.stream.XMLInputFactory;
import javax.xml.stream.XMLStreamException;
import org.codehaus.stax2.XMLInputFactory2;
import org.codehaus.stax2.XMLStreamReader2;
import org.getalp.dbnary.api.IStructureChecker;
import org.getalp.dbnary.cli.mixins.BatchExtractorMixin;
import org.getalp.dbnary.cli.mixins.SingleLanguageAsOptionMixin;
import org.getalp.dbnary.cli.mixins.WiktionaryIndexMixin;
import org.getalp.dbnary.languages.StructureCheckerFactory;
import org.getalp.dbnary.wiki.WikiText;
import org.getalp.wiktionary.WiktionaryIndexer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import picocli.CommandLine.Command;
import picocli.CommandLine.Mixin;
import picocli.CommandLine.Model.CommandSpec;
import picocli.CommandLine.ParentCommand;
import picocli.CommandLine.Spec;


@Command(name = "check", mixinStandardHelpOptions = true,
    header = "check the mediawiki syntax of all pages of a dump.",
    description = "This command parses all standard pages using the wiki-text parser then outputs "
        + "stats concerning the full parsing. You can use trace and debug options to switch on "
        + "debug messages generated by the parser and get a hint on all syntactic errors detected "
        + "by the parser.")
public class CheckWiktionaryQuality {

  private final Logger log = LoggerFactory.getLogger(CheckWiktionaryQuality.class);

  private static final XMLInputFactory2 xmlif;

  @Spec
  CommandSpec spec; // injected by picocli
  @ParentCommand
  protected DBnary parent; // picocli injects reference to parent command
  @Mixin
  private BatchExtractorMixin batch;
  @Mixin
  private SingleLanguageAsOptionMixin lm;
  @Mixin
  WiktionaryIndexMixin wi;

  static {
    try {
      xmlif = (XMLInputFactory2) XMLInputFactory2.newInstance();
      xmlif.setProperty(XMLInputFactory.IS_VALIDATING, Boolean.FALSE);
      xmlif.setProperty(XMLInputFactory.IS_SUPPORTING_EXTERNAL_ENTITIES, Boolean.FALSE);
      xmlif.setProperty(XMLInputFactory2.P_PRESERVE_LOCATION, Boolean.TRUE);
    } catch (Exception ex) {
      System.err.println("Cannot intialize XMLInputFactory while classloading WiktionaryIndexer.");
      throw new RuntimeException("Cannot initialize XMLInputFactory", ex);
    }
  }

  private IStructureChecker structureChecker;

  protected void read(String title, String page) {
    WikiText text = new WikiText(title, page);
    text.content();
  }


  protected void struct(String title, String page) {
    structureChecker.checkPage(title, page);
  }

  @Command(name = "syntax")
  public Integer checkSyntax() throws IOException {
    return check(this::read);
  }

  @Command(name = "structure", aliases = {"struct"})
  public Integer checkStructure() throws IOException {
    structureChecker =
        StructureCheckerFactory.getStructureChecker(lm.getLanguage(), batch.tdbDir());
    if (structureChecker == null) {
      spec.commandLine().getErr().println(
          String.format("Could not find a structure checker for %s. Exiting.", lm.getLanguage()));
      return -1;
    }
    structureChecker.setWiktionaryIndex(wi);

    return check(this::struct);
  }

  public Integer check(BiConsumer<String, String> consumer) throws IOException {
    // create new XMLStreamReader
    long startTime = System.currentTimeMillis();
    long totalRelevantTime = 0, relevantTimeOfLastThousands;
    int nbPages = 0, nbRelevantPages = 0;
    relevantTimeOfLastThousands = System.currentTimeMillis();

    XMLStreamReader2 xmlr = null;
    try {
      // pass the file name. all relative entity references will be
      // resolved against this as base URI.
      xmlr = xmlif.createXMLStreamReader(wi.getDumpFile());

      // check if there are more events in the input stream
      String title = "";
      String page = "";
      while (xmlr.hasNext()) {
        xmlr.next();
        if (xmlr.isStartElement() && xmlr.getLocalName().equals(WiktionaryIndexer.pageTag)) {
          title = "";
          page = "";
        } else if (xmlr.isStartElement()
            && xmlr.getLocalName().equals(WiktionaryIndexer.titleTag)) {
          title = xmlr.getElementText();
        } else if (xmlr.isStartElement() && xmlr.getLocalName().equals("text")) {
          page = xmlr.getElementText();
        } else if (xmlr.isEndElement() && xmlr.getLocalName().equals(WiktionaryIndexer.pageTag)) {
          if (!title.equals("")) {
            if (title.contains(":"))
              continue;
            nbPages++;
            if (nbPages < batch.fromPage()) {
              continue;
            }
            if (nbPages > batch.toPage()) {
              break;
            }
            try {
              consumer.accept(title, page);
            } catch (RuntimeException e) {
              System.err.println("Runtime exception while extracting  page<<" + title
                  + ">>, proceeding to next pages.");
              System.err.println(e.getMessage());
              // e.printStackTrace();
            }
            totalRelevantTime = (System.currentTimeMillis() - startTime);
            nbRelevantPages++;
            if (nbRelevantPages % 1000 == 0) {
              System.err.println("Extracted: " + nbRelevantPages + " pages in: "
                  + formatHMS(totalRelevantTime) + " / Average = "
                  + (totalRelevantTime / nbRelevantPages) + " ms/extracted page ("
                  + (System.currentTimeMillis() - relevantTimeOfLastThousands) / 1000 + " ms) ("
                  + nbPages + " processed Pages)");
              // System.err.println(" NbNodes = " + s.getNbNodes());
              relevantTimeOfLastThousands = System.currentTimeMillis();
            }
          }
        }
      }
      System.err.println("Extracted " + nbRelevantPages + " pages in: "
          + formatHMS(totalRelevantTime) + " (" + nbPages + " scanned Pages)");

    } catch (XMLStreamException ex) {
      log.error(ex.getLocalizedMessage());

      if (ex.getNestedException() != null) {
        log.error("  Nested Exception: " + ex.getNestedException().getLocalizedMessage());
      }
      throw new IOException("XML Stream Exception while reading dump", ex);
    } catch (Exception ex) {
      log.error("Unexpected Exception: ", ex);
    } finally {
      try {
        if (xmlr != null) {
          xmlr.close();
        }
      } catch (XMLStreamException ex) {
        log.error("Exception while closing xml stream. ", ex);
      }

    }
    return 0;
  }

  private String formatHMS(long durationInMillis) {
    Duration d = Duration.ofMillis(durationInMillis);
    long h = d.toHours();
    long m = d.toMinutes() % 60;
    long s = d.getSeconds() % 60;
    return String.format("%d:%2d:%2d", h, m, s);
  }

}
